version: "3.9"

services:
  web:
    build: ./web
    container_name: crypto-store-web
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - STRIPE_SECRET=${STRIPE_SECRET}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - FLW_SECRET=${FLW_SECRET}
      - PAYSTACK_SECRET=${PAYSTACK_SECRET}
      - BASE_URL=${BASE_URL}
    restart: unless-stopped
